New Enemy States
The enemies now have three states, they can patrol, chase, and attack (attack is there but it does nothing for now). I noticed that I keep getting the following error...

NullReferenceException: Object reference not set to an instance of an object
EnemyNavigation.OnDrawGizmosSelected () (at Assets/Scripts/EnemyNavigation.cs:117)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)"

I can still run the game so I don't yet know if this is a problem I need to address. Anyways, these were my references:
- https://www.youtube.com/watch?v=UjkSFoLxesw
- https://docs.unity3d.com/ScriptReference/AI.NavMesh.SamplePosition.html
- https://www.google.com/search?q=how+to+check+if+a+navagent+destination+is+on+Navmesh&sca_esv=8e300a61fb8ea468&rlz=1C1_____enUS1082US1082&sxsrf=ADLYWIIfB0gbhWaz5V0-umfT0azZwuARbQ%3A1731999888590&ei=kDg8Z4XcI6XU5NoPwufjyAc&ved=0ahUKEwiF5PCw6ueJAxUlKlkFHcLzGHkQ4dUDCA8&uact=5&oq=how+to+check+if+a+navagent+destination+is+on+Navmesh&gs_lp=Egxnd3Mtd2l6LXNlcnAiNGhvdyB0byBjaGVjayBpZiBhIG5hdmFnZW50IGRlc3RpbmF0aW9uIGlzIG9uIE5hdm1lc2gyBRAhGKABMgUQIRigATIFECEYoAEyBRAhGKABSOl9UM0NWL95cAJ4AZABAJgBjgGgAYsNqgEEMTYuMrgBA8gBAPgBAZgCFKACxg3CAgoQABiwAxjWBBhHwgIKECEYoAEYwwQYCsICCBAhGKABGMMEwgIGEAAYFhgewgILEAAYgAQYhgMYigXCAggQABiABBiiBMICBRAhGKsCwgIHECEYoAEYCsICBBAhGAqYAwCIBgGQBgiSBwQxNi40oAevdg&sclient=gws-wiz-serp